### ISSUE TITLE
Assignment #4: White Dwarf Timing

### ISSUE THREAD

**Issue by rxa254** [rxa254/ph237#11]
@zmarkcaltech, I've uploaded a first draft of a4.ipynb. Could you start filling in with some thoughts for assignment 4? We want to make the notebook so that we supply all the tedious details and the students can just work on the interesting parts so as to be able to estimate the WD array sensitivity.

1.  Angular response of a single pulsar timing signal to h+ and hx.
1. f_orb(t) for a WD binary with equal mass stars (M = 0.5 to 1.0)
1.

**Comment by zmarkcaltech** [comment]
It looks like right now a4.ipynb has large amounts of code copied and pasted from the solutions for a1 (so much so that I am confused). Is this correct or is there a more recent version of a4.ipynb that hasn't been pushed?

**Comment by zmarkcaltech** [comment]
Based on what is there right now, I think we need to provide at the very least for part (a)

(1) the equations for how to get the timing residuals as a function of the extra phase

For part (b) I'm not sure I completely understand the question. Is the aim to use the transfer function from extra phase induced by the background GWs to the Timing residual to map the corrections in the phase due to \dot P and W_p into an equivalent noise in the phase? Regardless, I think at the very least we need to provide

(1) the definition of the equivalent strain noise spectral density

**Comment by rxa254** [comment]
feel free to delete that stuff; its just placeholders for formatting
