### ISSUE TITLE
Binary Precession in HWK #3

### ISSUE THREAD

**Issue by rxa254** [rxa254/ph237#7]
How to go from nearly circular orbits to more eccentric orbits? Maybe we should just do it numerically?

**Comment by zmarkcaltech** [comment]
I think that the actually solution to the evolution equations for the semi-major p and the eccentricity e has to be done numerically. This is how Eric Poisson and Clifford Will did it in Figures 12.3 and 12.4 of their textbook "Gravity". 

Also, since I know that you are interested, in the same section they explain how to derive the evolution equations from the radiation reaction potentials. I have not worked through this section myself though.

**Comment by zmarkcaltech** [comment]
Hi Rana,

I have some thoughts, but my ideas seem to involve radical changes to the wording of the question. My ideas are motivated by Poission and WIll's discussion of the Hulse-Taylor Binary in Ch. 12 (although I still have not read all of the relevant sections of the chapter).

Namely, the physical effect that we want to verify with the Hulse-Taylor data is that dP/dt agrees with GR where P is the period. The reason that P changes with time is entirely due to radiation reaction and dP/dt can be computed using energy balance. However, in order to compare the data to the GR prediction for dP/dt, one needs to know the chirp mass. The chirp mass can be extracted from measurements of the precession of the pericenter of the orbit, the eccentricity of the orbit, and P. As you said during class, the dominant contribution to this effect is not radiation reaction. It is that orbits in Schwarzschild don't close. Hence this step can be done by considering massive geodesics in Schwarzschild, as you outlined.

Hence I propose the following:
In part (a), we go through a similar derivation to Carroll (ending in eq. 5.92) to derive the precision of the periolion in Schwarzschild. 

In part (b) we use the measured value of the precession of the pericenter, e, and P of the Hulse-Taylor system, given in table 12.1 of Poisson and WIll (who cite the references where they got the table) to  get the chirp mass. 

In part (c), we use energy balance to derive the evolution equation for P. We will provide them with the expressions for the angular momentum radiated to infinity and energy radiated to infinity in term of derivatives of the quadrupole moment.

in part (d) we numerically solve the evolution equations with the value of the chirp mass obtained in b. We can then compare to the measured value of dP/dt given in table 12.1 (or the cited references).

This would be a challenging problem. I have not worked through all of these steps yet myself. I can provide hints based on what I anticipate will happen and from expressions derived in Poisson and Will's textbook, but without doing the problem myself, I can't say much more. Perhaps it would be fine to simply outline this procedure in the problem set.

Let me know what you think. I realize that we have to get this done by class. I'm not sure that I will have time to make all of these changes tonight, but I may be able to find time tomorrow morning before class. Best,

Zach

**Comment by rxa254** [comment]
I think this would be more like what we would do in a GR class, but that's not really our goal here. Its more on that Bayesian inference that I was talking about. You can come by my office and lets talk about it.

**Comment by zmarkcaltech** [comment]
sure, I'll be right over, but I probably only have 15-20 minutes. See you in a few, 

Zach

**Comment by zmarkcaltech** [comment]
I just fixed this and pushed the changes.

The problem occurred on 4/24. Based on the Git history, it seems that you had a introduced an extra "//" at the end of line 51.
